jobs:
  - name: runsh-job-pub
    type: runSh
    allowPublicAccess: false
    steps:
      - IN: sample-pub
      - IN: tr1
      - TASK:
        - script: IN/sample-pub/gitRepo/echo.sh
    flags: job1
    
  - name: runcliscript-job-pub
    type: runCLI
    allowPublicAccess: true
    steps:      
      - IN: sample-scriptpvt
      - TASK:
        - script: IN/sample-scriptpvt/gitRepo/echo.sh
    flags: runcliscript-job-pub
  
  - name: sample_publicrepo_runCI
    type: runCI
    steps:
      - IN: sample_publicrepo_ciRepo
      - IN: tr2
  
  - name: runsh-jobrunCI-pub
    type: runSh
    steps:
      - IN: sample_publicrepo_runCI
      - IN: tr3
      - TASK:
        - script: ls
  
  - name: runcli-jobrunCI-pub
    type: runCLI
    steps:
      #- IN: sample_publicrepo_runCI
      - IN: tr4
      - TASK:
        - script: ls
        
  - name: manifest_dep_pub
    type: manifest
    allowPublicAccess: true
    steps:
      - IN: sample_img_pub 
    flags: manifest
    
  - name: runsh-job2-pub
    type: runSh
    allowPublicAccess: true
    steps:
      - IN: runsh-job-pub
      - TASK:
        - script: ls
    
  - name: runcliscript-job2-pub
    type: runCLI
    steps:      
      - IN: runcliscript-job-pub
      - TASK:
        - script: ls
      
  - name: sample-release-pub
    type: release
    allowPublicAccess: true
    steps:
      - IN: sample-version-pub
      - TASK: managed
        bump: rc
        
  - name: sample-ddcdeploy-pub
    type: deploy
    allowPublicAccess: true
    on_start:
      - NOTIFY: sample-email-pub
      - NOTIFY: sample-slack-pub
    steps:
      - IN: sample-ddccluster-pub
      - IN: manifest_dep_pub
      - IN: sample-params-pub
      - IN: sample-dopts-pub
    on_success:
      - NOTIFY: sample-email-pub
      - NOTIFY: sample-slack-pub
      
  - name: sample-provision-pub                                                 
    type: provision     
    allowPublicAccess: true
    steps:
      - IN: sample-files-pub
      
  - name: ar-jenkins                  # a memorable, unique name. this is how your job will be referred to in shippable pipelines
    type: jenkinsJob # The type of the job (should not be changed by the user)
    allowPublicAccess: true
    integration: "jenkins"   # The name of your Jenkins integration (created via accountSettings page)
    pointer:
      sourceName: "firstjob"          # The name of your Jenkins job
    steps:
      - OUT: "sample-files-pub"
